### ISSUE TITLE
"ERR_TOO_MANY_REDIRECTS" après installation et configuration

### ISSUE THREAD

**Issue by un-breton** [Merrick28/seedbox-docker#23]
Bonjour,
j'ai installé la dernière version en suivant les instructions sur un serveur dédié et Debian 10 fraichement installé.
Les variables ont été mises à jour avec mes informations.

fichier vars
# Domaine
export SERVER_BASE_URL=server
export DOMAIN_URL=mon-nom-de-domaine.xxx
export SERVER_IPV4= IP du serveur dedié
export EMAIL_FOR_SECURITY=postmaster@mon-nom-de-domaine.xxx
ainsi que les informations liés à Cloudflare

je n'ai rien modifié du fichier all.yml
j'ai par contre rajouté la ligne # Certificate Resolver dans le fichier docker-compose.yml (pour effectuer les tests).

L'installation se passe bien et l'inscription ACME et DNS se fait bien sous cloudflare, aucune erreur à l'exécution des scripts ("ansible-playbook secure.yml -i hosts" et "seedbox_system.sh -f ") 
Cependant, des que je tente d'accéder a l'URL indiqué après l'installation ( portainer-server.mon-nom-de-domaine.xxx ), la page indique ""ERR_TOO_MANY_REDIRECTS".
J'ai effectué plusieurs réinstallation complète du système, avec ou sans mot de passe admin (demandé lors de l'exécution du script  seedbox_system.sh -f ) 

quelqu'un a t il déjà rencontré ce problème ?
Merci !

**Comment by Merrick28** [comment]
Comment est ta configuration cloudflare ? De mémoire, dans ta config ssl, tu dois être en "complet"
![image](https://user-images.githubusercontent.com/3830148/157617445-6e5cebf1-5c6c-4122-adff-3097058ed1f6.png)

**Comment by un-breton** [comment]
Bonjour, c'étais en "Flexible" ...
En effet, ca fonctionne maintenant... Merci beaucoup !

**Comment by Merrick28** [comment]
Parfait, je cloture :)
