### ISSUE TITLE
Traefik v2.0.0

### ISSUE THREAD

**Issue by Chiledog** [Merrick28/seedbox-docker#5]
Just FYI. I got caught out with the release of Traefik 2.0.0. If you still support this maybe force v1.7.16 as a temporary solution.

**Comment by Merrick28** [comment]
Yes, just saw it this morning on another project. I will correct it asap.

**Comment by Merrick28** [comment]
Fixed by commit 3050c2536f3d48fa27366974e41d6c7e429ea55c

**Comment by Chiledog** [comment]
Merci dude! :)
The guys at D03 say "Hi!" ;)

**Comment by memento** [comment]
"Hi!"
Le D03, ce gang !

**Comment by Merrick28** [comment]
Hello D03 (still ?), the project has moved to traefik v2 at least... See README for updates
